ckb-js/kuai

.gitignore
package-lock.json
packages/core/__tests__/errors.ts
packages/core/__tests__/index.ts
packages/core/jest.config.js
packages/core/package.json
packages/core/src/errors-list.ts
packages/core/src/errors.ts
packages/core/src/index.ts
packages/core/src/params.ts
packages/core/src/runtime.ts
packages/core/src/task.ts
packages/core/src/type/index.ts
packages/core/src/type/runtime.ts
packages/core/tsconfig.json
tsconfig.json

create `kuaiproject/core` package & implement task system
task system design: https://github.com/ckb-js/kuai/issues/13

feat: implement task system

---

package-lock.json
packages/core/package.json
packages/core/src/builtin-tasks/index.ts
packages/core/src/builtin-tasks/mock.ts
packages/core/src/config/config-env.ts
packages/core/src/config/config-loading.ts
packages/core/src/config/index.ts
packages/core/src/constants.ts
packages/core/src/context.ts
packages/core/src/extenders.ts
packages/core/src/helper.ts
packages/core/src/index.ts
packages/core/src/project-structure.ts
packages/core/src/task-loader.ts
packages/core/src/type/runtime.ts
packages/core/src/typescript-support.ts

create `kuaiproject/core` package & implements task system 
task system design: https://github.com/ckb-js/kuai/issues/13

feat: kuai context

---

renovate.json

Remove homura and ironlu233 from the reviewer list of renovate

ci: remove some reviewers

---

docs/pre-design/input-output-layer.md

pre-design of Kuai Input/Output layer
preview: https://github.com/ckb-js/kuai/blob/feat/docs-io/docs/pre-design/input-output-layer.md

docs: io layer

---

package-lock.json
packages/cli/__tests__/__fixtures__/kuai-config-case/kuai.config.ts
packages/cli/__tests__/index.ts
packages/cli/jest.config.js
packages/cli/package.json
packages/cli/src/main.ts

integrate kuai/cli & kuai/core
task system design: https://github.com/ckb-js/kuai/issues/13

feat: integrate cli

---

package-lock.json
packages/io/__tests__/cor.ts
packages/io/jest.config.js
packages/io/package.json
packages/io/src/cor.ts
packages/io/src/types/index.ts
packages/io/tsconfig.json
packages/io/tsconfig.test.json

Resolve: https://github.com/ckb-js/kuai/issues/49

feat: implement io

---

packages/cli/__tests__/__fixtures__/kuai-config-case/kuai.config.ts
packages/cli/__tests__/index.ts
packages/cli/jest.config.js
packages/cli/src/main.ts
packages/core/src/errors-list.ts
packages/core/src/params.ts
packages/core/src/runtime.ts
packages/core/src/task.ts
packages/core/src/type/runtime.ts

feat: task support variadic param

---

renovate.json

Remove felicityin from the reviewer list of renovate

ci: remove one reviewer from reviewer list of renovate

---

packages/typeorm/examples/default-conn/package.json
packages/typeorm/examples/default-conn/src/app.ts
packages/typeorm/examples/default-conn/src/index.ts
packages/typeorm/examples/default-conn/src/user.entity.ts
packages/typeorm/examples/default-conn/src/user.service.ts
packages/typeorm/examples/default-conn/tsconfig.json
packages/typeorm/examples/kuai-entity/package.json
packages/typeorm/examples/kuai-entity/src/app.ts
packages/typeorm/examples/kuai-entity/src/index.ts
packages/typeorm/examples/kuai-entity/src/user.entity.ts
packages/typeorm/examples/kuai-entity/src/user.service.ts
packages/typeorm/examples/kuai-entity/tsconfig.json
packages/typeorm/examples/named-conn/package.json
packages/typeorm/examples/named-conn/src/app.ts
packages/typeorm/examples/named-conn/src/index.ts
packages/typeorm/examples/named-conn/src/user.entity.ts
packages/typeorm/examples/named-conn/src/user.service.ts
packages/typeorm/examples/named-conn/tsconfig.json
packages/typeorm/examples/relations/package.json
packages/typeorm/examples/relations/src/app.ts
packages/typeorm/examples/relations/src/entities/category.entity.ts
packages/typeorm/examples/relations/src/entities/index.ts
packages/typeorm/examples/relations/src/entities/post.entity.ts
packages/typeorm/examples/relations/src/entities/user.entity.ts
packages/typeorm/examples/relations/src/index.ts
packages/typeorm/examples/relations/src/services/category.service.ts
packages/typeorm/examples/relations/src/services/index.ts
packages/typeorm/examples/relations/src/services/post.service.ts
packages/typeorm/examples/relations/src/services/user.service.ts
packages/typeorm/examples/relations/tsconfig.json

feat: add examples for typeprom

---

package-lock.json
packages/io/__tests__/adapter.ts
packages/io/__tests__/cor.ts
packages/io/__tests__/listener.ts
packages/io/__tests__/router.ts
packages/io/jest.config.js
packages/io/package.json
packages/io/src/adapter.ts
packages/io/src/listener.ts
packages/io/src/router.ts
packages/io/src/types/index.ts

feat: implement kuai-router & listener

---

package-lock.json
packages/io/__tests__/adapter.ts
packages/io/__tests__/router.ts
packages/io/package.json
packages/io/src/adapter.ts
packages/io/src/cor.ts
packages/io/src/router.ts
packages/io/src/types/index.ts

- `KuaiRouter` support parse params payload
- `KoaRouterAdapter` support pass body &  query payload

feat(@kuai/io): support params

---

packages/samples/mvp-dapp/README.md
packages/samples/mvp-dapp/jest.config.ts
packages/samples/mvp-dapp/kuai.config.js
packages/samples/mvp-dapp/kuai.config.ts
packages/samples/mvp-dapp/package.json
packages/samples/mvp-dapp/tsconfig.json

1. remove unused jest config
2. update ts config to reduce nested directories in dist
3. add build:watch and start:prod commands in package.json

feat: refine config of mvp dapp

---

package-lock.json
packages/core/sample-projects/src/main.ts
packages/io/__tests__/adapter.ts
packages/io/package.json
packages/io/src/adapter.ts
packages/io/src/cor.ts
packages/io/src/router.ts
packages/io/src/types/index.ts
packages/models/src/actor/registry.ts
packages/samples/mvp-dapp/package.json
packages/samples/mvp-dapp/src/app.controller.ts
packages/samples/mvp-dapp/src/chain-source.ts
packages/samples/mvp-dapp/src/main.ts

- `kuai/io` support http status 
-  `mvp-dapp` controller add some params validate

feat: io support http status & add mvp controller validator

---

packages/samples/mvp-dapp/kuai.config.js
packages/samples/mvp-dapp/src/main.ts
packages/samples/mvp-dapp/src/type-extends.d.ts

- mvp dapp support lumos config

chore: mvp dapp add lumos config

---

packages/models/src/actor/registry.ts
packages/models/src/store/json-storage.ts
packages/models/src/store/store.ts
packages/samples/mvp-dapp/src/app.controller.ts
packages/samples/mvp-dapp/src/const.ts
packages/samples/mvp-dapp/src/omnilock/omnilock.model.ts
packages/samples/mvp-dapp/src/record/record.model.ts
packages/samples/mvp-dapp/src/views/tx.view.ts

It can return `inputs, outputs, outputs_data`, but need to build a tx by these data.

fix: Fix request success.

---

README.md
packages/samples/mvp-dapp/README.md

1. add docs about how to build libraries
2. add docs about how to run the mvp dapp
Ref: https://github.com/ckb-js/kuai/issues/146

docs: add development docs

---

package-lock.json
packages/samples/mvp-dapp/.env.example
packages/samples/mvp-dapp/kuai.config.js
packages/samples/mvp-dapp/package.json
packages/samples/mvp-dapp/src/main.ts
packages/samples/mvp-dapp/src/type-extends.d.ts

feat: mvp dapp support dotenv

---

packages/models/__tests__/store/store.ts
packages/models/src/store/store.ts
packages/models/src/utils/decorator/provider.ts
packages/samples/mvp-dapp/src/app.controller.ts
packages/samples/mvp-dapp/src/main.ts
packages/samples/mvp-dapp/src/omnilock/omnilock.model.ts

Script is the most general property of a store so it was added for facility. It can be combined with "cell pattern" later
Besides, a `meta` property which includes `capacity` is added for better user experience.

feat: add script metadata in store

---

.github/workflows/deploy.yaml
docker/mvp-dapp/Dockerfile
docker/mvp-dapp/hooks.json
docker/mvp-dapp/redeploy.sh
packages/samples/mvp-dapp/src/main.ts

- need add some secret key
- DOCKER_USER
- DOCKER_TOKEN
- DEPLOY_WEBHOOK_URL

feat: add deploy action

---

README.md
packages/samples/mvp-dapp/README.md

Preview: https://github.com/ckb-js/kuai/blob/add-docs-of-mvp/packages/samples/mvp-dapp/README.md

docs: add a concise docs for the mvp dapp

---

packages/core/jest.config.js
packages/core/src/builtin-tasks/index.ts
packages/core/src/builtin-tasks/test.ts
packages/core/src/type/runtime.ts
packages/samples/mvp-dapp/__tests__/index.ts
packages/samples/mvp-dapp/kuai.config.js
packages/samples/mvp-dapp/package.json

- add builtin test action
- add simple test for kuai-mvp-dapp

feat: add builtin test action

---

.github/workflows/deploy.yaml

reason: [Waiting for a runner to pick up this job...](https://github.com/actions/runner-images/issues/6002)

fix: slove deploy action faild error

---

packages/core/src/builtin-tasks/contract.ts

Supplementary 0 2 multisig example

fix: promise order bug

---

.github/workflows/deploy.yaml
.github/workflows/test.yaml
Development.md
README.md
docker/mvp-dapp/Dockerfile
lerna.json
package-lock.json
package.json

More information about `lerna` v7 https://github.com/lerna/lerna/releases/tag/7.0.0

feat: update lerna to v7

---

package-lock.json
packages/common/package.json

1. add @ckb-js/lumos in the common module

fix: fix shadow dependencies

---

README.md
docs/tutorials/mvp-dapp.md
packages/samples/mvp-dapp/README.md

This PR adds the development guide for building the MVP dapp in **docs/tutorials/**
Ref:
- Introduction: https://github.com/ckb-js/kuai/issues/228

docs: update introduction of kuai

---

.github/release-drafter.yml
.github/workflows/release-draft.yml

This PR adds an action to create a release draft when rc/v* branch is merged into main branch

ci: add an action to create release draft

---

packages/core/sample-projects/kuai.config.ts
packages/core/sample-projects/src/main.ts
packages/core/sample-projects/src/type-extends.ts
packages/models/src/actor/actor.ts
packages/samples/mvp-dapp/kuai.config.js
packages/samples/mvp-dapp/src/main.ts
packages/samples/mvp-dapp/src/type-extends.d.ts

Add the options parameter for connecting Redis.

chore: Add option for redis

---

package-lock.json
packages/common/package.json

fix(common): add dependency env-paths to common package

---

packages/core/src/helper.ts

Load ts-node on demand during kuai initialization

chore: load ts-node on demand
